"""Pydantic schemas for request/response validation."""
from .base import BaseSchema, BaseResponse, PaginatedResponse, ErrorResponse, TimestampSchema
from .category import (
    CategoryBase,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    CategoryListResponse,
    CategoryStats,
)
from .achievement import (
    AchievementRarity,
    VerificationStatus,
    AchievementCategory,
    AchievementBase,
    AchievementResponse,
    AchievementListResponse,
    UserAchievementResponse,
    AchievementWithProgress,
    UserAchievementsResponse,
    CertificateData,
    AchievementDetailResponse,
    VerifyAchievementRequest,
    VerifyAchievementResponse,
    AwardAchievementResponse,
)

__all__ = [
    "BaseSchema",
    "BaseResponse",
    "PaginatedResponse",
    "ErrorResponse",
    "TimestampSchema",
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryListResponse",
    "CategoryStats",
    # Achievements
    "AchievementRarity",
    "VerificationStatus",
    "AchievementCategory",
    "AchievementBase",
    "AchievementResponse",
    "AchievementListResponse",
    "UserAchievementResponse",
    "AchievementWithProgress",
    "UserAchievementsResponse",
    "CertificateData",
    "AchievementDetailResponse",
    "VerifyAchievementRequest",
    "VerifyAchievementResponse",
    "AwardAchievementResponse",
]
